name: Test

on:
    pull_request: {}
    push:
        branches: master
        tags: "*"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8

            - name: Install Poetry
              uses: abatilo/actions-poetry@v2.1.0
              with:
                  poetry-version: 1.1.6

            - run: poetry install
            - run: poetry run python -m pytest